### ISSUE TITLE
AttributeError: module 'websocket' has no attribute 'WebSocketApp'

### ISSUE THREAD

**Issue by KshitizSharmaV** [polygon-io/client-python#12]
Hi, I tried importing and it gave following error.

> _>>> from polygon import WebSocketClient, STOCKS_CLUSTER
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/kshitizsharma/miniconda3/lib/python3.6/site-packages/polygon/__init__.py", line 1, in <module>
>     from .websocket import WebSocketClient, STOCKS_CLUSTER, FOREX_CLUSTER, CRYPTO_CLUSTER
>   File "/Users/kshitizsharma/miniconda3/lib/python3.6/site-packages/polygon/websocket/__init__.py", line 1, in <module>
>     from .websocket_client import WebSocketClient, STOCKS_CLUSTER, FOREX_CLUSTER, CRYPTO_CLUSTER
>   File "/Users/kshitizsharma/miniconda3/lib/python3.6/site-packages/polygon/websocket/websocket_client.py", line 12, in <module>
>     class WebSocketClient:
>   File "/Users/kshitizsharma/miniconda3/lib/python3.6/site-packages/polygon/websocket/websocket_client.py", line 21, in WebSocketClient
>     on_error: Optional[Callable[[websocket.WebSocketApp, str], None]] = None):
> AttributeError: module 'websocket' has no attribute 'WebSocketApp'__

_

**Comment by KshitizSharmaV** [comment]
My apologies it's not an issue of Polygon it's dependency websocket-client. I will give this here if anybody else gets stuck

[https://stackoverflow.com/questions/42141689/attributeerror-module-object-has-no-attribute-websocketapp](https://stackoverflow.com/questions/42141689/attributeerror-module-object-has-no-attribute-websocketapp)
