### ISSUE TITLE
No module named 'polygon' error

### ISSUE THREAD

**Issue by radikal9** [polygon-io/client-python#16]
I am trying to run a script that uses Polygon. I have the module installed:

(base) [name]-MacBook-Pro:client-python-master [name]$ pip3 install /Users/[name]/Downloads/polygon_api_client-0.1.2-py3-none-any.whl 
Requirement already satisfied: polygon-api-client==0.1.2 from file:///Users/[name]/Downloads/polygon_api_client-0.1.2-py3-none-any.whl in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (0.1.2)
Requirement already satisfied: websockets==8.0.2 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from polygon-api-client==0.1.2) (8.0.2)
Requirement already satisfied: websocket-client==0.56.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from polygon-api-client==0.1.2) (0.56.0)
Requirement already satisfied: six in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from websocket-client==0.56.0->polygon-api-client==0.1.2) (1.14.0)
(base) [name]-MacBook-Pro:client-python-master [name]$ 

But when I try to run the script (MacBook Pro running 10.15.4 I get the following error:

>>> from polygon import RESTClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'polygon'
>>> 

Not sure what to do next. I have uninstalled and installed using Pip3 install polygon-api-client and using the .whl installer (as shown above). I have also gone through the dependancies list and made sure that each of them are installed. 

Thank you for any help you can provide.

**Comment by jbonzo** [comment]
I attempted to install the module in the docker container for python and only came across one issue which is being addressed #18, but once I installed that package it then worked for me. 

I am going to try and reproduce the issue on my machine (Mac OS 1.15.5) and I will use [pyenv](https://github.com/pyenv/pyenv) to use python 3.8.2

# What I did:
```
▶ docker run -it python:3.8.2 /bin/bash
root@d967ccab01b5:/# pip install polygon-api-client
Collecting polygon-api-client
  Downloading polygon_api_client-0.1.2-py3-none-any.whl (20 kB)
Collecting websocket-client==0.56.0
  Downloading websocket_client-0.56.0-py2.py3-none-any.whl (200 kB)
     |████████████████████████████████| 200 kB 7.0 MB/s
Collecting websockets==8.0.2
  Downloading websockets-8.0.2.tar.gz (57 kB)
     |████████████████████████████████| 57 kB 8.1 MB/s
Collecting six
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Building wheels for collected packages: websockets
  Building wheel for websockets (setup.py) ... done
  Created wheel for websockets: filename=websockets-8.0.2-cp38-cp38-linux_x86_64.whl size=77395 sha256=3f67fd2b56463f082646bb69c390fb8ce43a688cef206ef47bc35604af7250bd
  Stored in directory: /root/.cache/pip/wheels/bb/bf/d6/aed9bc2f7159f6ee9d74bd59befaf2fcc8d61b747e89cd0a59
Successfully built websockets
Installing collected packages: six, websocket-client, websockets, polygon-api-client
Successfully installed polygon-api-client-0.1.2 six-1.15.0 websocket-client-0.56.0 websockets-8.0.2
WARNING: You are using pip version 20.1; however, version 20.1.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
root@d967ccab01b5:/# python
Python 3.8.2 (default, Apr 23 2020, 14:22:33)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from polygon import RESTClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/polygon/__init__.py", line 2, in <module>
    from .rest import RESTClient
  File "/usr/local/lib/python3.8/site-packages/polygon/rest/__init__.py", line 1, in <module>
    from .client import RESTClient
  File "/usr/local/lib/python3.8/site-packages/polygon/rest/client.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
>>>
root@d967ccab01b5:/# pip install requests==2.22.0
Collecting requests==2.22.0
  Downloading requests-2.22.0-py2.py3-none-any.whl (57 kB)
     |████████████████████████████████| 57 kB 755 kB/s
Collecting idna<2.9,>=2.5
  Downloading idna-2.8-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 79 kB/s
Collecting chardet<3.1.0,>=3.0.2
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 421 kB/s
Collecting certifi>=2017.4.17
  Downloading certifi-2020.4.5.1-py2.py3-none-any.whl (157 kB)
     |████████████████████████████████| 157 kB 719 kB/s
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading urllib3-1.25.9-py2.py3-none-any.whl (126 kB)
     |████████████████████████████████| 126 kB 919 kB/s
Installing collected packages: idna, chardet, certifi, urllib3, requests
Successfully installed certifi-2020.4.5.1 chardet-3.0.4 idna-2.8 requests-2.22.0 urllib3-1.25.9
WARNING: You are using pip version 20.1; however, version 20.1.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
root@d967ccab01b5:/# python
Python 3.8.2 (default, Apr 23 2020, 14:22:33)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from polygon import RESTClient
>>> from polygon import *
>>>
root@d967ccab01b5:/# exit
```

**Comment by jbonzo** [comment]
I tried again on my Mac with python 3.8.2 and it worked fine for me. It looks like you are trying to install the package from a local wheel. have you tried `pip install polygon-api-client`?

**Comment by radikal9** [comment]
@jbonzo Thank you for checking this. I am going to reinstall python 3.8.x and try again. Once I do, I will update you. Again, thank you for your thorough testing and help.

**Comment by radikal9** [comment]
Decided to go through each module againto make sure it was correctly installed and got this error come up. Not sure if it has anything to do with the issue I am having:

Collecting six
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
ERROR: alpaca-trade-api 0.46 has requirement urllib3<1.25, but you'll have urllib3 1.25.9 which is incompatible.
Installing collected packages: six
  Attempting uninstall: six
    Found existing installation: six 1.14.0
    Uninstalling six-1.14.0:
      Successfully uninstalled six-1.14.0
Successfully installed six-1.15.0

Do I need to uninstall urlilib3 1.25.9 and install version 1.24?

**Comment by jbonzo** [comment]
Oh geez. Isn't python dependency management fun?

I would really recommend you checking out virtualenv or pyenv. Those are great tools used to isolate separate project dependencies.

If this is all the same project then maybe the problem will still persist.

Can you be a little more specific on the steps you are taking to  get to this point?
