### ISSUE TITLE
WebSocketClient not found

### ISSUE THREAD

**Issue by ravening** [polygon-io/client-python#45]
Im trying to run the sample python code for websocket but Im getting module not found.
I have installed both websocket and polygon packages using pip but no luck. Running on python 3.6

```
Python 3.6.9 (default, Apr 18 2020, 01:56:04)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from polygon import WebSocketClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/polygon.py", line 4, in <module>
    from polygon import WebSocketClient, STOCKS_CLUSTER
ImportError: cannot import name 'WebSocketClient'
>>>
```

```
pip install polygon-api-client
Requirement already satisfied: polygon-api-client in /usr/local/lib/python3.6/dist-packages
```

```
pip install websocket-client
Requirement already satisfied: websocket-client in /usr/local/lib/python3.6/dist-packages
```

**Comment by imzeeshan** [comment]
Same issue for me.

**Comment by jmy48** [comment]
the docs / examples are outdated. WebSocketClient is now in `polygon.websocket`

`from polygon.websocket import WebSocketClient, STOCKS_CLUSTER`

**Comment by keshavreddy2021** [comment]
@jmy48 that didn't work. 

```
Traceback (most recent call last):
  File "/Users/keshavreddy/Deserve/Projects/botBuddy/polygon.py", line 5, in <module>
    from polygon.websocket import WebSocketClient, STOCKS_CLUSTER
  File "/Users/keshavreddy/Deserve/Projects/botBuddy/polygon.py", line 5, in <module>
    from polygon.websocket import WebSocketClient, STOCKS_CLUSTER
ModuleNotFoundError: No module named 'polygon.websocket'; 'polygon' is not a package
```

**Comment by matichenor** [comment]
We have a new version of the library and new doc which addresses this problem.  Thanks for calling it to our attention.

See the [Getting Started](https://polygon-api-client.readthedocs.io/en/latest/Getting-Started.html) section in our docs or view the [examples](https://github.com/polygon-io/client-python/blob/master/examples) directory.

**Comment by matichenor** [comment]
Hi Jeff,

Can you please raise a new issue to describe your problem?  It will make it
easier for the team to investigate than tracking against this old issue.
Thank you!

_
Matt Tichenor

**Comment by johnny-vulture** [comment]
non of your stuff seems to be working i keep getting this error


Traceback (most recent call last):
  File "C:\Users\User\Desktop\experiments\Stock\polygon.py", line 1, in <module>
    import polygon
  File "C:\Users\User\Desktop\experiments\Stock\polygon.py", line 2, in <module>
    from polygon import RESTClient
ImportError: cannot import name 'RESTClient' from partially initialized module 'polygon' (most likely due to a circular import) (C:\Users\User\Desktop\experiments\Stock\polygon.py)

**Comment by justinpolygon** [comment]
> none of your stuff seems to be working i keep getting this error, i tried the websockets and REST examples with and without my api key
> 
> Traceback (most recent call last): File "C:\Users\User\Desktop\experiments\Stock\polygon.py", line 1, in import polygon File "C:\Users\User\Desktop\experiments\Stock\polygon.py", line 2, in from polygon import RESTClient ImportError: cannot import name 'RESTClient' from partially initialized module 'polygon' (most likely due to a circular import) (C:\Users\User\Desktop\experiments\Stock\polygon.py)

Hi @johnny-vulture, do you have the polygon client library installed? Can you run `pip install -U polygon-api-client`. If you're still getting the same error can you please run `pip list` and paste the results. From the errors it looks like the client isn't installed. Thanks.
